export const ORDER_CREATE_BEGIN = 'ORDER_CREATE_BEGIN';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_ERROR = 'ORDER_CREATE_ERROR';

export const ORDER_DETAILS_BEGIN = 'ORDER_DETAILS_BEGIN';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_ERROR = 'ORDER_DETAILS_ERROR';

export const ORDER_LIST_BEGIN = 'ORDER_LIST_BEGIN';
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const ORDER_LIST_ERROR = 'ORDER_LIST_ERROR';

export const ORDER_PAY_BEGIN = 'ORDER_PAY_BEGIN';
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS';
export const ORDER_PAY_ERROR = 'ORDER_PAY_ERROR';
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET';

export const ORDER_LIST_MY_USER_BEGIN = 'ORDER_LIST_MY_USER_BEGIN';
export const ORDER_LIST_MY_USER_SUCCESS = 'ORDER_LIST_MY_USER_SUCCESS';
export const ORDER_LIST_MY_USER_ERROR = 'ORDER_LIST_MY_USER_ERROR';
export const ORDER_LIST_MY_USER_RESET = 'ORDER_LIST_MY_USER_RESET';
