export const PRODUCT_LIST_BEGIN = 'PRODUCT_LIST_BEGIN';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_ERROR = 'PRODUCT_LIST_ERROR';

export const PRODUCT_DETAILS_BEGIN = 'PRODUCT_DETAILS_BEGIN';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_ERROR = 'PRODUCT_DETAILS_ERROR';

export const PRODUCT_DELETE_BEGIN = 'PRODUCT_DELETE_BEGIN';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_ERROR = 'PRODUCT_DELETE_ERROR';
