export const USER_LOGIN_BEGIN = 'USER_LOGIN_BEGIN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_BEGIN = 'USER_REGISTER_BEGIN';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR';

export const USER_GET_PROFILE_BEGIN = 'USER_GET_PROFILE_BEGIN';
export const USER_GET_PROFILE_SUCCESS = 'USER_GET_PROFILE_SUCCESS';
export const USER_GET_PROFILE_ERROR = 'USER_GET_PROFILE_ERROR';
export const USER_GET_PROFILE_RESET = 'USER_GET_PROFILE_RESET';

export const USER_UPDATE_PROFILE_BEGIN = 'USER_UPDATE_PROFILE_BEGIN';
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_ERROR = 'USER_UPDATE_PROFILE_ERROR';
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET';

export const USER_LIST_BEGIN = 'USER_LIST_BEGIN';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_ERROR = 'USER_LIST_ERROR';
export const USER_LIST_RESET = 'USER_LIST_RESET';

export const USER_DELETE_BEGIN = 'USER_DELETE_BEGIN';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_ERROR = 'USER_DELETE_ERROR';
